### ISSUE TITLE
Actor for Registered & Unregistered

### ISSUE THREAD

**Issue by garemoko** [tesapp/tes-xapi#13]
It's not clear who the actor for Registered & Unregistered is - the person registering or the person being registered?

Consider using substatements.

**Comment by ekron** [comment]
I agree, it is unclear. The verb is [defined by ADL](http://adlnet.gov/expapi/verbs/registered) as:

**definition**: register (record in writing; enter into a book of names or events or transactions)
**usage**: Indicates the actor registered for a learning activity

So there's a change in meaning between definition and xAPI usage? The intention is to use registered in the "usage" sense. 

So the notion is that the actor property of the Registered and Unregistered statements is the *person who registered for or unregistered from the event*. It's analogous to a person (the actor) filling his or her own name on a form to register for a meeting, conference or whatever it may be.  In this case Kylie (the actor) is registering to attend the meeting:

    Kylie Attendee registered to attend the meeting.

This doesn't preclude another statement being made that asserts that another actor accepted that registration.

    Jeff Admin accepted (Kylie Attendee registered to attend the meeting).

Or other possibilities:

    Jeff Admin rejected (Kylie Attendee registered to attend the meeting).
    Jeff Admin acknowledged (Kylie Attendee registered to attend the meeting).

But those sorts of statements are probably out of scope? To me, they belongs the attendee management recipe?

I'll tentatively updated the text with added clarification, but I'm very much open to other suggestions.

**Comment by garemoko** [comment]
Agree this is is very confusing and will flag this to ADL. I don't think we should quote and challenge the confusion in the recipe though; just say this is what the verb means in our recipe. Though technically incorrect to do so, I'd be inclined to use the registry definition as authoritative as this won't change. The minor adjustments look good to me. 

Agree that accepting/rejecting should be out of scope for this. I wouldn't be adverse to having statement to represent something like Andrew Registered Sean for an event. I'm sure those could be achieve using sub statements, but not sure what the sub statement verb would be. Perhaps it would be registered and the main verb would be something like 'caused'.

**Comment by garemoko** [comment]
Note, this is the relevant section of the spec that implies that using the registry definition is ok in the event that the hosted metadata is weird: https://github.com/adlnet/xAPI-Spec/blob/1.0.3/xAPI.md#metadata-consumer-requirements

**Comment by andyjohnson** [comment]
I guess I don't see a conflict.  I'd say always rely on the usage as what the verb is intended to do.  The definition is essentially used as disambiguation from other definitions of the same lexicon.  Here is the list of "registered" verbs from Princeton Wordnet (our authoritative source):

S: (v) register (record in writing; enter into a book of names or events or transactions)
S: (v) file, register (record in a public office or in a court of law) "file for divorce"; "file a complaint"
S: (v) register (enroll to vote) "register for an election"
S: (v) record, register (be aware of) "Did you register any change when I pressed the button?"
S: (v) read, register, show, record (indicate a certain reading; of gauges and instruments) "The thermometer showed thirteen degrees below zero"; "The gauge read `empty'"
S: (v) cross-file, register (have one's name listed as a candidate for several parties)
S: (v) register (show in one's face) "Her surprise did not register"
S: (v) register (manipulate the registers of an organ)
S: (v) register (send by registered mail) "I'd like to register this letter"
S: (v) register (enter into someone's consciousness) "Did this event register in your parents' minds?"

If you look at these, we don't have a clear electronic course registration, but the idea of entering a record in writing of it is very conceptually similar (think of a wedding registry), especially given the alternatives.

**Comment by jhaag75** [comment]
Thanks for sharing this Andrew! I don't believe there is a conflict. The metadata properties for definition and usage have different purposes. The definition is authoritative and we are adopting the meaning of these from wordnet in our ADL vocabulary (e.g. registered could be dereferenced here: http://wordnet-rdf.princeton.edu/wn31/202477113-v). The usage is just to add more details on the intent. We need to better document this as part of the vocabulary working group. Also, you can assign it to me for action as one of thing things we need to add as an update to the spec and metadata options/requirements (perhaps 2.0?). We will have better guidance and metadata requirements for verbs in the upcoming months as that is one of the primary goals of the vocab working group.

As you pointed out Andrew, since the "hosted metadata is weird" then there isn't a problem. Just use your recipe approach for now. 

And as Andy pointed out, there are different definitions of registered in wordnet. We picked the one that most closely resembles our intent for SCORM and ADL. There's nothing stopping someone from coining the same spelling of this "registered" verb, but using a different meaning (and intent). This can best be resolved by machines via RDF and linked data. That's why we are trying to come up with more definitive metadata properties and some good working examples illustrating this as part of the vocab working group too. The current ADL verbs are a bad example. We are working on cleaning those up as well and improving human readability as well by defining a schema for all of the properties. I think it's fine to just use your recipe example for their use case for now until we have better guidance in place.

**Comment by andyjohnson** [comment]
I don't know if the current ADL verbs are a BAD example, but there is certainly room for improvement (RDF, PURLs, associated activities, other metadata).  Generic verbs that go across many domains like these are also hard to provide too much definition to as well.  I'm looking forward to providing great examples of verbs as communities of practice coin them (CMI5 will be a good litmus test).

**Comment by garemoko** [comment]
Thanks for the responses ADL team!

I think this is now resolved so will close.
